# 02 - Introduction to NumPy
**NumPy**, short for **Numerical Python**, is an open-source library essential for scientific computing in Python. It offers efficient operations on numerical data, particularly with its powerful array structures.

## Key Features of NumPy
1. **Multidimensional Arrays**
    - `ndarray`: The core data structure in NumPy is the `ndarray`, which supports efficient storage and manipulation of large datasets with multiple dimensions. Arrays can have any number of dimensions (more on this later).

2. **Vectorized Operations**
    - NumPy allows operations on entire arrays without explicit loops, making computations faster and more concise.

3. **Mathematical Functions**
    - Provides a wide array of mathematical functions for operations on arrays, including trigonometric functions, statistics, and linear algebra.

4. **Efficiency**
    - NumPy is much faster than the same functionality implemented directly on native Python. It is also very flexible in terms of accessing and manipulating individual elements or subsets of arrays.

## Installation
To install NumPy, you can use `pip`:

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


Once installed, you can import it as follows:

In [2]:
import numpy as np

You only need to import a library **once** in your notebook to be able to use it in subsequent cells.

## Arrays
A NumPy `array` is a data structure that allows you to store a collection of elements, usually numbers, in one or more dimensions.

### One-dimensional Array
A one-dimensional (1D) `array` in NumPy is a data structure that contains a sequence of elements in a single dimension. It is similar to a list in Python, but with the performance and functionality advantages offered by NumPy.

<p align="center">
  <img src="imgs/intro_to_numpy1.png" alt="Alt text" width="700" height="400">
</p>

A 1D array can be created using the `array` function of the library with a list of elements as an argument. For example:

In [7]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

This will create a 1D array with elements 1, 2, 3, 4 and 5. The array elements must be of **the same data type**. If the elements are of different types, NumPy will try to convert them to the same type if possible.

You can check the data type of the array,

In [8]:
# To check the data type of `array`
type(array)

numpy.ndarray

In a 1D array, we can access the elements using indexes, modify them and perform mathematical operations on the whole array efficiently. Below are some operations that can be performed using the above array:

In [9]:
# Access the third element (i.e. the element at index 2)
print(array[2])

3


In [14]:
print(f"Original array: {array}")

# Change the value of the second element (i.e. the element at index 1)
array[1] = 7
print(f"Updated array: {array}")

Original array: [1 2 3 4 5]
Updated array: [1 7 3 4 5]


In [15]:
print(f"Original array: {array}")

# Add 10 to all elements
array += 10
print(f"Updated array: {array}")

Original array: [1 7 3 4 5]
Updated array: [11 17 13 14 15]


In [16]:
print(f"Original array: {array}")

# Calculate the sum of the elements
sum_all = np.sum(array)
print(f"Sum of array: {sum_all}")

Original array: [11 17 13 14 15]
Sum of array: 70


### N-dimensional Array
A multidimensional or **n-dimensional array** in NumPy is a data structure that organizes elements in multiple dimensions (axes). These arrays allow you to represent more complex data structures, such as matrixes (2D array, 2 axes), tensors (3D array, 3 axes) and higher-dimensional structures.

<p align="center">
  <img src="imgs/intro_to_numpy2.png" alt="Alt text" width="700" height="400">
</p>

An N-dimensional array can also be created using the `array` function of the library. For example, if we want to create a 2D array:

In [7]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# To get the shape (dimensions) of the array
np.shape(array_2d)

(3, 3)

If we now wanted to create a 3D array, we would have to think of it as a list of arrays:

In [23]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
# To get the shape (dimensions) of the array
np.shape(array_3d)

(2, 2, 2)

As with 1D arrays, the elements in a multidimensional array are accessible via indexes, operations can be performed on them, and so on.

As we add more dimensions, the basic principle remains the same: each additional dimension can be considered an additional level of nesting. However, on a practical level, working with arrays of more than 3 or 4 dimensions can become more complex and less intuitive.

For example, we have to do 3 levels of nesting to access a single element from a 3D array:

In [25]:
array_3d[0]

array([[1, 2],
       [3, 4]])

In [26]:
array_3d[0][0]

array([1, 2])

In [27]:
array_3d[0][0][0]

1

In [28]:
# You can also perform the same operations as a 1D array
print(f"Original array:\n{array_3d}")

# Add 10 to all elements
array_3d += 10
print(f"\nUpdated array:\n{array_3d}")

Original array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Updated array:
[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]


### Functions
NumPy provides a large number of predefined functions that can be applied directly to the data structures seen above or to Python's own data structures (lists, arrays, etc.). Some of the most commonly used in data analysis are:

In [32]:
# Create an array for the example
arr = np.array([1, 2, 3, 4, 5])

# Adding n to each element
print(f"Original array: {arr}")
print("Add 5 to each element:", np.add(arr, 5))

Original array: [1 2 3 4 5]
Add 5 to each element: [ 6  7  8  9 10]


In [34]:
# Multiplying each element by n
print(f"Original array: {arr}")
print("Multiply each element by 3:", np.multiply(arr, 3))

Original array: [1 2 3 4 5]
Multiply each element by 3: [ 3  6  9 12 15]


In [39]:
# Logarithmic: Take log(x) for each x in the array
print(f"Original array: {arr}")
print("log(x):", np.log(arr))

Original array: [1 2 3 4 5]
log(x): [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [38]:
# Exponential: take e^x for each x in the array
print(f"Original array: {arr}")
print("e^x:", np.exp(arr))

Original array: [1 2 3 4 5]
e^x: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [40]:
# Statistical Functions
print(f"Original array: {arr}")
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Maximum value:", np.max(arr))
print("Maximum value index:", np.argmax(arr))
print("Minimum value:", np.min(arr))
print("Minimum value index:", np.argmin(arr))
print("Sum of all elements:", np.sum(arr))

Original array: [1 2 3 4 5]
Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0
Maximum value: 5
Maximum value index: 4
Minimum value: 1
Minimum value index: 0
Sum of all elements: 15


In [41]:
# Rounding Functions
arr_decimal = np.array([1.23, 2.47, 3.56, 4.89])
print(f"Original array: {arr_decimal}")
print("Rounding:", np.around(arr_decimal))
print("Minor integer (floor):", np.floor(arr_decimal))
print("Major integer (ceil):", np.ceil(arr_decimal))

Original array: [1.23 2.47 3.56 4.89]
Rounding: [1. 2. 4. 5.]
Minor integer (floor): [1. 2. 3. 4.]
Major integer (ceil): [2. 3. 4. 5.]


## Summary
NumPy is an indispensable library for numerical computations in Python. It provides efficient array operations and a comprehensive set of mathematical functions, making it a fundamental tool for data science, machine learning, and scientific computing. Understanding how to use NumPy arrays and functions will significantly enhance your ability to process and analyze numerical data.

## Additional Resources
1. [NumPy Official Documentation](https://numpy.org/doc/stable/)

2. [NumPy Quickstart Tutorial](https://numpy.org/doc/stable/user/quickstart.html)

3. [DataCamp's Introduction to NumPy](https://www.datacamp.com/courses/intro-to-python-for-data-science)

4. [Codecademy's Learn NumPy](https://www.codecademy.com/learn/learn-numpy)

5. [Corey Schafer's NumPy Series (YouTube)](https://www.youtube.com/playlist?list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6Ww)

6. [NumPy Tutorial for Beginners (YouTube)](https://www.youtube.com/watch?v=8Mpc9ukltVA)